category_keywords = {
    "personal_injury": {
        "injury": 1.8,
        "injured": 1.8,
        "hurt": 1.5,
        "harmed": 1.4,
        "pain": 1.2,
        "suffering": 1.0,
        "pain and suffering": 2.5,
        "physical injury": 2.4,
        "bodily injury": 2.6,
        "serious injury": 2.4,
        "permanent injury": 2.5,
        "minor injury": 1.6,
        "back injury": 2.0,
        "neck injury": 2.0,
        "head injury": 2.1,
        "brain injury": 2.5,
        "tbi": 2.4,
        "broken bone": 2.3,
        "fracture": 2.2,
        "sprain": 1.8,
        "burn": 2.0,
        "burned": 2.0,
        "cut": 1.5,
        "bleeding": 1.6,
        "bruise": 1.3,
        "scar": 1.4,
        "disability": 2.0,
        "disabled": 1.8,
        "medical treatment": 2.0,
        "medical bills": 2.3,
        "hospital": 1.8,
        "hospitalized": 2.2,
        "emergency room": 2.1,
        "er": 1.4,
        "doctor": 1.2,
        "surgery": 2.2,
        "rehab": 1.8,
        "therapy": 1.4,
        "ambulance": 1.8,
        "recovery": 1.2,
        "damages": 1.4,
        "compensation": 1.9,
        "settlement": 1.8,
        "claim": 0.65,
        "lawsuit": 0.55,
        "sue": 0.55,
        "negligence": 2.8,
        "negligent": 2.6,
        "liability": 2.0,
        "liable": 2.0,
        "duty of care": 2.8,
        "breach of duty": 2.8,
        "caused my injury": 2.4,
        "unsafe": 1.2,
        "dangerous": 1.3,
        "hazard": 1.4,
        "hazardous": 1.4,
        "unsafe condition": 2.3,
        "dangerous condition": 2.4,
        "premises liability": 3.0,
        "property owner": 1.8,
        "store": 1.0,
        "grocery store": 1.8,
        "restaurant": 1.4,
        "mall": 1.3,
        "parking lot": 1.6,
        "apartment complex": 1.7,
        "landlord": 1.6,
        "wet floor": 2.8,
        "slippery floor": 2.8,
        "spill": 1.8,
        "slip": 1.8,
        "slipped": 2.0,
        "trip": 1.6,
        "tripped": 1.8,
        "fall": 1.7,
        "fell": 1.9,
        "slip and fall": 3.5,
        "trip and fall": 3.5,
        "stairs": 1.4,
        "broken stairs": 2.2,
        "uneven sidewalk": 2.3,
        "sidewalk": 1.3,
        "ice": 1.5,
        "snow": 1.2,
        "car accident": 3.2,
        "auto accident": 3.2,
        "vehicle accident": 3.0,
        "motor vehicle accident": 3.2,
        "crash": 2.1,
        "collision": 2.2,
        "rear ended": 2.7,
        "rear end": 2.5,
        "hit by a car": 2.8,
        "pedestrian": 2.0,
        "crosswalk": 1.7,
        "truck accident": 2.8,
        "motorcycle accident": 2.8,
        "bike accident": 2.5,
        "bicycle accident": 2.5,
        "uber accident": 2.6,
        "lyft accident": 2.6,
        "drunk driver": 2.7,
        "distracted driver": 2.6,
        "whiplash": 2.2,
        "insurance claim": 2.0,
        "fault": 1.7,
        "at fault": 2.0,
        "dog bite": 3.0,
        "bitten by a dog": 3.0,
        "bitten": 2.8,
        "got bitten": 2.9,
        "i was bitten": 3.0,
        "was bitten": 2.9,
        "bit me": 2.6,
        "dog attack": 2.9,
        "attacked by another dog": 3.0,
        "attacked by a dog": 3.0,
        "separating the dogs": 2.4,
        "animal attack": 2.5,
        "bite": 1.7,
        "bit": 1.7,
        "assault": 1.3,
        "battery": 1.3,
        "wrongful death": 3.0,
        "death": 1.8,
        "fatal": 1.8,
        "killed": 1.8,
        "construction accident": 2.8,
        "worksite accident": 2.5,
        "defective product": 2.7,
        "product liability": 3.0,
        "malfunction": 1.8,
        "defective": 2.1,
        "medical malpractice": 3.0,
        "malpractice": 2.8,
        "nursing home abuse": 2.9,
        "exposure": 1.5,
        "toxic": 1.6,
        "poisoning": 2.2
    },

    "employment_labor": {
        "job": 0.5,
        "work": 0.45,
        "employee": 1.6,
        "employer": 1.8,
        "boss": 1.7,
        "manager": 1.4,
        "supervisor": 1.7,
        "coworker": 1.5,
        "coworkers": 1.5,
        "human resources": 1.8,
        "hr": 1.5,
        "workplace": 1.8,
        "company": 0.45,
        "office": 0.4,
        "shift": 1.3,
        "schedule": 1.1,
        "employment": 2.0,
        "labor": 1.8,
        "hired": 1.5,
        "fired": 2.8,
        "fire me": 2.8,
        "fire": 2.0,
        "terminated": 2.8,
        "termination": 2.8,
        "let go": 2.5,
        "laid off": 2.4,
        "layoff": 2.4,
        "wrongful termination": 3.4,
        "wrongful discharge": 3.2,
        "resigned": 1.5,
        "forced to resign": 2.8,
        "constructive discharge": 3.3,
        "quit": 1.2,
        "demoted": 2.2,
        "demotion": 2.2,
        "promotion": 1.2,
        "discipline": 1.4,
        "disciplined": 1.4,
        "write up": 1.5,
        "written up": 1.5,
        "suspended": 2.0,
        "probation": 1.5,
        "retaliation": 3.2,
        "retaliate": 3.0,
        "retaliated": 3.0,
        "workplace retaliation": 3.4,
        "reported": 1.3,
        "reported unsafe conditions": 3.3,
        "reported harassment": 3.1,
        "reported discrimination": 3.1,
        "whistleblower": 3.2,
        "whistleblowing": 3.0,
        "complaint": 1.4,
        "filed a complaint": 2.5,
        "reported misconduct": 2.8,
        "unsafe working conditions": 3.3,
        "unsafe workplace": 3.1,
        "workplace safety": 2.5,
        "osha": 2.8,
        "labor board": 2.4,
        "nlrb": 2.8,
        "union": 2.3,
        "collective bargaining": 3.0,
        "organizing": 1.8,
        "strike": 2.0,
        "wage": 2.0,
        "wages": 2.0,
        "pay": 1.5,
        "salary": 1.7,
        "hourly": 1.5,
        "minimum wage": 3.0,
        "overtime": 3.0,
        "unpaid overtime": 3.2,
        "not paid": 2.4,
        "late paycheck": 2.3,
        "paycheck": 2.0,
        "tips": 1.6,
        "commission": 1.6,
        "bonus": 1.3,
        "deduction": 1.5,
        "paystub": 1.6,
        "wage theft": 3.2,
        "misclassified": 2.8,
        "independent contractor": 2.7,
        "contractor": 1.4,
        "exempt": 2.0,
        "non exempt": 2.0,
        "meal break": 2.0,
        "rest break": 2.0,
        "time card": 1.8,
        "timesheet": 1.8,
        "discrimination": 3.0,
        "discriminated": 3.0,
        "harassment": 3.0,
        "harassed": 3.0,
        "hostile work environment": 3.5,
        "hostile workplace": 3.2,
        "sexual harassment": 3.5,
        "racial discrimination": 3.4,
        "gender discrimination": 3.4,
        "pregnancy discrimination": 3.4,
        "age discrimination": 3.4,
        "disability discrimination": 3.4,
        "religious discrimination": 3.4,
        "national origin discrimination": 3.4,
        "eeoc": 2.8,
        "reasonable accommodation": 3.0,
        "accommodation": 1.9,
        "ada": 2.7,
        "fmla": 2.7,
        "medical leave": 2.5,
        "family leave": 2.5,
        "sick leave": 2.1,
        "leave of absence": 2.3,
        "maternity leave": 2.4,
        "paternity leave": 2.4,
        "workers comp": 2.2,
        "workers compensation": 2.5,
        "benefits": 1.5,
        "unemployment": 1.8,
        "background check": 1.7,
        "drug test": 1.8,
        "employment contract": 2.5,
        "non compete": 2.8,
        "noncompete": 2.8,
        "nda": 2.0,
        "severance": 2.3,
        "offer letter": 1.8,
        "intern": 1.4,
        "internship": 1.4
    },

    "copyright": {
        "copyright": 3.2,
        "copyrighted": 3.0,
        "copyright infringement": 3.8,
        "infringement": 2.5,
        "intellectual property": 2.3,
        "ip": 1.2,
        "license": 2.2,
        "licensed": 2.2,
        "licensing": 2.2,
        "license violation": 3.2,
        "open source": 3.5,
        "opensource": 3.3,
        "source code": 3.0,
        "code": 0.35,
        "codebase": 2.7,
        "repository": 1.5,
        "repo": 1.4,
        "github": 1.8,
        "gitlab": 1.5,
        "software": 1.8,
        "app": 0.35,
        "application": 0.35,
        "program": 0.35,
        "commercial use": 3.0,
        "commercially": 2.0,
        "for profit": 2.7,
        "generate profit": 2.8,
        "selling software": 2.8,
        "sell software": 2.8,
        "sell my software": 2.9,
        "reuse": 2.0,
        "reusing": 2.0,
        "copy": 1.8,
        "copied": 1.8,
        "copying": 1.8,
        "modify": 1.7,
        "modified": 1.7,
        "modification": 1.8,
        "adapt": 1.6,
        "adaptation": 1.8,
        "derivative work": 3.5,
        "derivative": 2.8,
        "fork": 2.0,
        "forked": 2.0,
        "redistribute": 2.8,
        "redistribution": 2.8,
        "distribution": 2.0,
        "publish": 1.5,
        "published": 1.5,
        "distribute": 2.0,
        "private use": 2.0,
        "internal use": 2.0,
        "copyleft": 3.3,
        "permissive license": 3.0,
        "gpl": 3.5,
        "lgpl": 3.4,
        "agpl": 3.5,
        "mit license": 3.3,
        "apache license": 3.3,
        "bsd license": 3.2,
        "mozilla public license": 3.2,
        "mpl": 2.8,
        "license terms": 3.0,
        "attribution": 2.7,
        "notice": 0.75,
        "copyright notice": 3.0,
        "retain notice": 2.5,
        "disclose source": 3.0,
        "must disclose source": 3.2,
        "viral license": 2.8,
        "proprietary": 2.3,
        "closed source": 2.5,
        "compatible license": 3.0,
        "license compatibility": 3.2,
        "software license": 3.0,
        "api": 2.5,
        "apis": 2.5,
        "interface": 2.0,
        "declaring code": 3.2,
        "method names": 2.1,
        "class names": 2.0,
        "package structure": 2.4,
        "library": 1.8,
        "sdk": 1.8,
        "framework": 1.7,
        "interoperability": 2.8,
        "compatibility": 2.4,
        "reverse engineer": 3.0,
        "reverse engineering": 3.2,
        "decompile": 2.7,
        "decompiled": 2.7,
        "decompilation": 2.7,
        "fair use": 3.4,
        "transformative": 2.8,
        "transformative use": 3.0,
        "parody": 2.0,
        "dmca": 3.0,
        "anti circumvention": 3.2,
        "circumvention": 3.0,
        "takedown": 2.4,
        "cease and desist": 2.5,
        "piracy": 2.3,
        "pirated": 2.3,
        "content": 0.35,
        "image": 1.2,
        "photo": 1.2,
        "music": 1.2,
        "video": 1.2,
        "book": 0.45,
        "article": 0.35,
        "text": 0.3,
        "copying code": 3.0,
        "use this code": 2.2,
        "can i use this code": 3.0,
        "can i use this library": 3.0,
        "can i use open source": 3.4,
        "can i sell this": 2.3,
        "copyright claim": 2.7,
        "copyright strike": 2.4,
        "oracle": 1.8,
        "google v oracle": 3.5,
        "jacobsen v katzer": 3.5,
        "sega": 1.6,
        "sega v accolade": 3.5
    }
}